
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "Firstname":"Mercy",
    "Lastname":"chep",
    "Senderemail": "mercynenoh22@gmail.com",
    "Password": "mercy12!"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "Senderemail": "mercynenoh22@gmail.com",
    "Password": "mercy12!"
}

###
GET http://localhost:5000/user/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIkZpcnN0bmFtZSI6Ik1lcmN5IiwiTGFzdG5hbWUiOiJjaGVwIiwiU2VuZGVyZW1haWwiOiJtZXJjeW5lbm9oMjJAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpc3NlbnQiOjEsImlzZGVsZXRlZCI6MCwiaWF0IjoxNjYzNTg2MjA0LCJleHAiOjE2NjM1ODk4MDR9.6DFJgfZVV3NSSiZ4EiTslFDF-n3QaIRmLNHXWY3etbo
###

GET http://localhost:5000/user/all
Content-Type: application/json

###

POST  http://localhost:5000/parcels/add
Content-Type: application/json

{
       "Adress": "Nanyuki",
      "Senderemail": "mercy.chepngenoh@student.moringaschool.com",
      "RecepientEmail": "mercynenoh22@gmail.com",
      "parcelname": "Parcel",
      "weight": 37783,
      "Date": "2022-09-12",
      "lat": 0,     
      "lng": 34,
      "TruckNo": "KGF 779h",
      "TrackingNo": "632788",
      "Price": 4748
}


####
POST  http://localhost:5000/parcels/add
Content-Type: application/json

{
      "Adress": "Nanyuki",
      "Senderemail": "mercynenoh22@gmail.com",
      "RecepientEmail": "onetjjjwo@gmail.com",
      "parcelname": "GIFTS",
      "weight": 37783,
      "Date": "2022-09-12",
      "lat": 0,     
      "lng": 34,
      "TruckNo": "KKDD779h",
      "TrackingNo": "632788",
      "Price": 4748
}
###
GET  http://localhost:5000/parcels/get
Content-Type: application/json

####
PUT  http://localhost:5000/parcels/update/39
Content-Type: application/json

####
DELETE   http://localhost:5000/parcels/delete/40
Content-Type: application/json

####
GET  http://localhost:5000/parcels/56678
Content-Type: application/json
####
GET  http://localhost:5000/parcels/sentparcels/mercynenoh22@gmail.com
Content-Type: application/json

####
GET  http://localhost:5000/parcels/receivedparcels/new@gmail.com
Content-Type: application/json